export default cartData = [
  {
    food: "Beef Burger",
    id: 1343,
    price: 1500,
    totalPrice: 1500,
    quantity: 1,
    restaurant: "Sweet Sensation",
  },
  {
    food: "Nut Burger",
    id: 1456,
    price: 2000,
    totalPrice: 2000,
    quantity: 1,
    restaurant: "Sweet Sensation",
  },
  {
    food: "Fried Rice",
    id: 13557,
    price: 1300,
    totalPrice: 1300,
    quantity: 1,
    restaurant: "Sweet Sensation",
  },
  {
    food: "Ofada Rice",
    id: 32467,
    price: 1800,
    totalPrice: 1800,
    quantity: 1,
    restaurant: "Sweet Sensation",
  },
  {
    food: "Coconut Rice",
    id: 8633,
    price: 2500,
    totalPrice: 2500,
    quantity: 1,
    restaurant: "Sweet Sensation",
  },
];
