const food = [
  {
    action: "",
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 1,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FFriedRice.png?alt=media&token=28918d1d-c89e-455e-b9e2-cfd3282fa7fd",
    minutesAway: "30 minutes",
    name: "Rice",
    price: 1500,
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    action: "",
    distance: "1.1 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 2,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FBreadAndBeans.png?alt=media&token=27022d71-ee93-4663-ace2-43b600943542",
    minutesAway: "25 minutes",
    name: "Bread and Beans",
    price: 1500,
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    action: "",
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 3,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FSpaghetti.png?alt=media&token=944bbe1d-97d2-4d40-8d2e-26569d079860",
    minutesAway: "33 minutes",
    name: "Spaghetti",
    price: 1500,
    restaurantName: "Mama Put",
    type: "food",
    quantity: 1,
  },
  {
    action: "",
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 4,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FOfadaRice.png?alt=media&token=e0b7dc30-99c0-4ecb-902b-4e6594f02c24",
    minutesAway: "30 minutes",
    name: "Ofada Rice",
    price: 1500,
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.7 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 21,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FwhiteRice.png?alt=media&token=290bc3b3-d52d-434a-bebc-ccea579a51ea",
    minutesAway: "33 minutes",
    name: "White Rice",
    price: 1500,
    restaurantName: "Mama Chi Chi",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.1 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 22,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FFriedRice.png?alt=media&token=28918d1d-c89e-455e-b9e2-cfd3282fa7fd",
    minutesAway: "25 minutes",
    name: "Fried Rice",
    price: 1500,
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.7 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 23,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FriceNplantain.png?alt=media&token=b233db16-cf83-46b6-a95f-1424dbce5254",
    minutesAway: "35 minutes",
    name: "Rice and Plantain",
    price: 1500,
    restaurantName: "Mama Chi Chi",
    type: "food",
    quantity: 1,
  },
];

export default food;
