const snacks = [
  {
    distance: "1.5 km",
    foodDetail: "Beef steak mince, Olive oil, Rolls\nKetchup, Egg",
    id: 9,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FbeefBurger.png?alt=media&token=98aaf696-c792-4569-8dc7-93f067640344",
    minutesAway: "30 minutes",
    name: "Beef Burger",
    price: "1500",
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.1 km",
    foodDetail: "Seasoned ground beef, Cheese,\nLettuce, Tomato",
    id: 10,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FkubieBurger.png?alt=media&token=8a3e2e2a-ca39-4ca9-af6f-e0d4e4fcc4f7",
    minutesAway: "25 minutes",
    name: "Kubie Burger",
    price: "1500",
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Mixed nuts, Chickpeas, Spices,\nHerbs, Lettuce,Sliced tomato",
    id: 11,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FnutBurger.png?alt=media&token=0766f2ac-f668-4a7c-b8b0-a01c86536d84",
    restaurantName: "Mr Biggs",
    minutesAway: "30 minutes",
    name: "Nutburger",
    price: "1500",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Mixed nuts, Chickpeas, Spices,\nHerbs, Lettuce,Sliced tomato",
    id: 29863,
    imageUrl:
      "https://forkify-api.herokuapp.com/images/IMG_67561180x180c6a2.jpg",
    restaurantName: "Mr Biggs",
    minutesAway: "30 minutes",
    name: "Banana Cream Pie",
    price: "1500",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Mixed nuts, Chickpeas, Spices,\nHerbs, Lettuce,Sliced tomato",
    id: 208972,
    imageUrl: "https://forkify-api.herokuapp.com/images/TPW_1850d7c8.jpg",
    restaurantName: "Mr Biggs",
    minutesAway: "30 minutes",
    name: "Chili Pie",
    price: "1500",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Mixed nuts, Chickpeas, Spices,\nHerbs, Lettuce,Sliced tomato",
    id: 2908761,
    imageUrl:
      "https://forkify-api.herokuapp.com/images/best_pizza_dough_recipe1b20.jpg",
    restaurantName: "Mr Biggs",
    minutesAway: "30 minutes",
    name: "Pizza Dough",
    price: "1500",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.1 km",
    foodDetail: "Ground turkey, Garlic, Onion,\nHerbs, Lettuce,Tomato, Avocado",
    id: 12,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "25 minutes",
    name: "Turkey Burger",
    price: "1500",
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 13,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "30 minutes",
    name: "Roast Turkey",
    price: "1500",
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.1 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 14,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "25 minutes",
    name: "Grilled Turkey Breast",
    price: "1500",
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 15,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "30 minutes",
    name: "Turkey Meatballs",
    price: "1500",
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 16,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "25 minutes",
    name: "Turkey Sausage",
    price: "1500",
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
  {
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    distance: "1.5 km",
    id: 17,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "30 minutes",
    name: "Roast Chiken",
    price: "1500",
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 18,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "30 minutes",
    name: "Grilled Chiken Breast",
    restaurantName: "SweetSensation",
    price: "1500",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 19,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "30 minutes",
    name: "Chicken Meatballs",
    price: "1500",
    restaurantName: "Mr Biggs",
    type: "food",
    quantity: 1,
  },
  {
    distance: "1.5 km",
    foodDetail: "Rolls, beef steak mince, olive oil,\nkethcup, egg",
    id: 20,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/react-practice-3b04d.appspot.com/o/food%2FturkeyBurger.png?alt=media&token=3a7ac7d8-12fa-4dbf-a95d-77b1c719b532",
    minutesAway: "25 minutes",
    name: "Chicken Sausage",
    price: "1500",
    restaurantName: "Sweet Sensation",
    type: "food",
    quantity: 1,
  },
];

export default snacks;
