export default Object.freeze({
  ADDRESS: "Address",
  CART: "CartScreen",
  CHECKOUT: "Checkout",
  DISH_DETAILS: "Dish Details",
  EDITCARD: "EditCard",
  FAVOURITE: "Favourite",
  FOOD: "Foods",
  FORGOTPASSWORD: "Forgot Password",
  FULLLIST: "Full List",
  HOME: "Home Screen",
  LOGIN: "LogIn",
  NEWCARD: "NewCard",
  ONBOARDING: "Onboarding",
  PAYMENTCARDS: "PaymentCards",
  PERSONALINFO: "PersonalInfo",
  PROFILE: "Profile",
  RECENT: "Recent",
  RESETPASSWORD: "Reset Password",
  RESTAURANT: "Restaurants",
  RESTAURANT_DISHES: "Restaurant Dishes",
  RESTAURANT_DISH_CATEGORY: "Restaurant Dish Category",
  SEARCH: "Search",
  SIGNUP: "SignUp",
  SNACKS: "Snacks",
  VERIFICATION: "Verification",
});
